export const FETCH_AMORTISATION = 'FETCH_AMORTISATION'
//export type FETCH_AMORTISATION = typeof FETCH_AMORTISATION
export const FETCH_AMORTISATION_REQUEST = 'FETCH_AMORTISATION_REQUEST'
export const FETCH_AMORTISATION_ERROR = 'FETCH_AMORTISATION_ERROR'
export const SET_AMORTISATION = 'SET_AMORTISATION'
